services:
  postgres:
    image: postgres:18.3
    container_name: postgres-hackaton
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: qohash
      POSTGRES_USER: qohash
      POSTGRES_DB: hackathon
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
